Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Turn the Page - Metallica");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("On a long and lonesome highway");
Console.WriteLine("East of Omaha");
Console.WriteLine("You can listen to the engines moanin");
Console.WriteLine("Out this one-note song");
Console.WriteLine("You'd think about the woman");
Console.WriteLine("Or the girl you knew the night before");
Console.WriteLine("");
Console.WriteLine("But your thoughts will soon be wanderin");
Console.WriteLine("The way they always do");
Console.WriteLine("When you're ridin' 16 hours");
Console.WriteLine("There's nothin' much to do");
Console.WriteLine("And you don't feel much like ridin'");
Console.WriteLine("You just wish the trip was through");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Here I am, on the road again");
Console.WriteLine("There I am, up on the stage");
Console.WriteLine("There I go playin' the star again");
Console.WriteLine("There I go, turn the page");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("So you walk into this restaurant");
Console.WriteLine("All strung out from the road");
Console.WriteLine("And you feel the eyes upon you");
Console.WriteLine("As you're shakin' off the cold");
Console.WriteLine("You pretend it doesn't bother you");
Console.WriteLine("But you just want to explode");
Console.WriteLine("");
Console.WriteLine("Yeah, most times you can't hear 'em talk");
Console.WriteLine("Other times you can");
Console.WriteLine("All the same old clichés");
Console.WriteLine("Is it woman, is it man?");
Console.WriteLine("And you always seem outnumbered");
Console.WriteLine("You don't dare make a stand");
Console.WriteLine("Make your stand");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("Here I am, on the road again");
Console.WriteLine("There I am, up on the stage");
Console.WriteLine("Here I go playin' the star again");
Console.WriteLine("There I go, turn the page");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("Oh-oh, out there in the spotlight");
Console.WriteLine("You're a million miles away");
Console.WriteLine("Every ounce of energy");
Console.WriteLine("You try and give away");
Console.WriteLine("As the sweat pours out your body");
Console.WriteLine("Like the music that you play, yeah");
Console.WriteLine("");
Console.WriteLine("Later in the evenin");
Console.WriteLine("As you lie awake in bed");
Console.WriteLine("With the echoes of the amplifiers");
Console.WriteLine("Ringin' in your head");
Console.WriteLine("You smoke the day's last cigarette");
Console.WriteLine("Rememberin' what she said");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("What she said");
Console.WriteLine("Yeah, and here I am, on the road again");
Console.WriteLine("There I am, up on the stage");
Console.WriteLine("Here I go playin' the star again");
Console.WriteLine("There I go, turn the page");
Console.ResetColor();
Console.WriteLine("");
Console.WriteLine("And there I go");
Console.WriteLine("Turn that page");
Console.WriteLine("There I go, yeah, yeah");
Console.WriteLine("There I go, yeah, yeah");
Console.WriteLine("");
Console.WriteLine("Here I go, yeah");
Console.WriteLine("Here I go, yeah");
Console.WriteLine("There I go");
Console.WriteLine("There I go");
Console.WriteLine("And I'm gone");
